[workspace]
resolver = "2"
members = [
    "string",
    "vec"
]

[workspace.package]
version = "0.9.5"
edition = "2024"
repository = "https://github.com/saulvaldelvira/tiny-vec"
authors = ["Saúl Valdelvira <saul@saulv.es>"]
license = "GPL-3.0-only"
readme = "README"
